# Generated by Django 3.2.16 on 2022-11-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('max_people', models.IntegerField()),
                ('qty_bathrooms', models.IntegerField()),
                ('pet_frendly', models.BooleanField()),
                ('cleaning_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
